version: '3.5'

services:

  consul:
    image: consul:latest
    command: agent -server -ui -node=server1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - consul-net

  gateway-service:
    restart: on-failure
    build: gateway-service/.
    image: webclient-showcase/gateway-service:1
    ports:
      - "8000:8000"
    networks:
      - consul-net
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500

  otp-service:
    restart: on-failure
    build: otp-service/.
    image: webclient-showcase/otp-service:1
    volumes:
      - ${PWD}:/logs/otp
    ports:
      - "8001:8001"
    networks:
      - consul-net
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=test
      - POSTGRES_USER=kmandalas
      - POSTGRES_PASSWORD=passepartout
      - NOTIFICATION_SERVICE_HOST=notification-service
      - NOTIFICATION_SERVICE_PORT=8005
      - NUMBER-INFORMATION_SERVICE_HOST=number-information-service
      - NUMBER-INFORMATION_SERVICE_PORT=8006

  customer-service:
    restart: on-failure
    build: customer-service/.
    image: webclient-showcase/customer-service:1
    ports:
      - "8002:8002"
    networks:
      - consul-net
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=test
      - POSTGRES_USER=kmandalas
      - POSTGRES_PASSWORD=passepartout

  notification-service:
    restart: on-failure
    build: notification-service/.
    image: webclient-showcase/notification-service:1
    ports:
      - "8005:8005"
    networks:
      - consul-net

  number-information-service:
    restart: on-failure
    build: number-information-service/.
    image: webclient-showcase/number-information-service:1
    ports:
      - "8006:8006"
    networks:
      - consul-net

  postgres:
    image: postgres:latest
    restart: always
    networks:
      - consul-net
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: kmandalas
      POSTGRES_PASSWORD: passepartout
    ports:
      - "5432:5432"

  jaeger:
    image: jaegertracing/all-in-one:1.8
    ports:
      - "16686:16686"
      - "9411:9411"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

networks:
  consul-net:
    driver: bridge